#!/usr/bin/perl

# Perform memory health checks on a VMWare ESX(i) host
# v1, sschneid@gmail.com

package check_esx_memory;

use Getopt::Long;
use VMware::VIRuntime;

use strict;



my $self = check_esx_memory->init();

my $view = Vim::find_entity_view( view_type => 'HostSystem' );

my ( $mem );

$mem->{'use'} = $view->summary->quickStats->overallMemoryUsage;
$mem->{'total'} = $view->hardware->memorySize / 1048576;
$mem->{'utilization'} = int( 100 * $mem->{'use'} / $mem->{'total'} );
#$mem->{'free'} = $mem->{'total'} - $mem->{'use'};

Util::disconnect();

my ( $status );
my ( $exitcode );

if ( $mem->{'utilization'} > $self->{'var'}->{'warn'} ) {
    $status = 'WARNING';
    $exitcode = 1;
}

if ( $mem->{'utilization'} > $self->{'var'}->{'crit'} ) {
    $status = 'CRITICAL';
    $exitcode = 2;
}

$status ||= 'OK';
$exitcode ||= 0;

print "MEMORY $status - used = $mem->{'utilization'}%";

if ( $self->{'var'}->{'perfdata'} ) {
    print ' | ';
    print "usage=$mem->{'utilization'}%;$self->{'var'}->{'warn'};$self->{'var'}->{'crit'}";
}

print "\n";
exit $exitcode;


sub init {
    my $self = bless {}, shift;

    $self->GetOptions(
        'host|hostname=s' => \$self->{'var'}->{'hostname'},
        'username|u=s' => \$self->{'var'}->{'username'},
        'password|p=s' => \$self->{'var'}->{'password'},

        'warning=s' => \$self->{'var'}->{'warn'},
        'critical=s' => \$self->{'var'}->{'crit'},
        'perfdata|f' => \$self->{'var'}->{'perfdata'}
    ) || { $self->{'var'}->{'help'} = 1 };

    unless (
        (
            $self->{'var'}->{'hostname'} &&
            $self->{'var'}->{'username'} &&
            $self->{'var'}->{'password'}
        ) &&
        (
            $self->{'var'}->{'warn'} &&
            $self->{'var'}->{'crit'}
        )
    ) {
        $self->{'var'}->{'help'} = 1;
    }

    if ( $self->{'var'}->{'help'} ) {
        print qq(Type 'perldoc $0' for more options and information\n\n);
        print qq(USAGE: $0 -h <host> -u <user> -p <pass> -w <warn> -c <crit> );
        print qq([option]...\n);
        exit( 1 );
    }

    Util::connect(
        'https://' . $self->{'var'}->{'hostname'} . '/sdk/webService',
        $self->{'var'}->{'username'},
        $self->{'var'}->{'password'}
    );

    return $self;
}
