#!/usr/bin/perl -w

use strict;

# This Nagios plugin monitors DHCP pool usage. However the output is so large that standard NRPE can't
# transit enough data for all the pools. This plugin gzips its output and base64encs it for transmission
# with NRPE. At the Nagios server end, you will need to read the output with check_nrpe_gz_b64 rather than
# the standard check_nrpe.

# Read in warn/crit thresholds or accept sensible defaults
my $warn = $ARGV[0];
my $crit = $ARGV[1];
if (!defined($warn)) { $warn = 80; }
if (!defined($crit)) { $crit = 90; }

# Initialise warn and crit flags
my $warnflag = 0;
my $critflag = 0;
my $perfdata;

# Get DHCP pool data and split it into lines
my $input = `/usr/bin/dhcpd-pools -c /etc/dhcp/dhcpd.conf -l /var/lib/dhcpd/dhcpd.leases -L02 | egrep -v "^[a-z0-9\.\-]* +0 "`;
if ($input eq '') {
	# The test failed failed. Check SELinux audit.log and don't forget to disable dontaudit filtering,
	# by using semodule -DB. Also make sure you are running this on a real DHCP server!
	print &encode('UNKNOWN - test went wrong');
	exit 3;
}
my @pools = split(/\n/, $input);
my %total;

foreach my $line (@pools) {
	my @split = split(/\s+/, $line);

	# Check to see if this triggers an alert
	if ($split[3] > $crit) {
		# Critical
		$critflag = 1;
	} elsif ($split[3] > $warn) {
		# Warning
		$warnflag = 1;
	}

	# Append this to perfdata
	$perfdata .= " $split[0]=$split[3]%;$warn;$crit,";

	# Add the size/total to the summary pool data
	$split[0] =~ m/(.*)-\d+$/;
	$total{$1}{'size'}  += $split[1];
	$total{$1}{'used'} += $split[2];
}

# Add the totalled perfdata for % and absolute - TODO
foreach my $key (keys %total)
	{
	my $percent = ($total{$key}{'used'}/$total{$key}{'size'})*100;
	# $perfdata .= " $key-average=$percent%;$warn;$crit";

	my $totalwarn = int($warn*$total{$key}{'size'}/100);
	my $totalcrit = int($crit*$total{$key}{'size'}/100);
	$perfdata .= " $key-totals=$total{$key}{'used'};$totalwarn;$totalcrit;0;$total{$key}{'size'}";
	}

# See what status we should output
my $status;
if ($critflag) {
	$status = "CRITICAL - one or more pools more than $crit% full";
	print &encode("$status|$perfdata");
	exit 2;
} elsif ($warnflag) {
	$status = "WARNING - one or more pools more than $warn% full";
	print &encode("$status|$perfdata");
	exit 1;
} else {
	$status = "OK - all pools less than $warn% full";
	print &encode("$status|$perfdata");
	exit 0;
}

# Shouldn't ever hit this line, but if we do, something is b0rked
print &encode('UNKNOWN - something is b0rked!');
exit 3;

sub encode {
	# gzip our data and base64enc it
	my $data = shift;
	my $encdata = `echo "$data" | gzip - | base64`;
	return $encdata;
}
