#!/bin/bash
# Version 2.0
# Date: 27/2/08
# Author: Eduardo kalil <ekalil@gmail.com>
#
# O plugin tem a função de mostar o tempo que o S.O esta ativo
# The plugin has the function to show the time that this active SO
#######################################################################

STATE_OK=0

DAY=`uptime | awk '{ print $4 }'| cut -c1-4 `
HOUR=`uptime | awk '{ print $3 }' | cut -c2`

if [ "$DAY" == "days" ] ; then
 DIA=`uptime | awk '{ print $3 }'`
 HORA=`uptime | awk '{ print $5}' | cut -f1 -d":"`
 MIN=`uptime | awk '{ print $5}' | cut -f2 -d":" |  cut -c1,2`
      echo "System uptime $DIA days $HORA hours $MIN minutes"
exit $STATE_OK

fi

if [ "$HOUR" == ":" ] ; then

 HORA=`uptime | awk '{ print $3}' | cut -c1`
 MIN=`uptime | awk '{ print $3}' | cut -f2 -d":" |  cut -c1,2`
 echo "System uptime $HORA hours $MIN minutes"
 exit $STATE_OK

else

 MIN=`uptime | awk '{ print $3 }'`
 echo "System uptime $MIN minutes"
 exit $STATE_OK

fi
